### ISSUE TITLE
Remove "request.addListener('end'"

### ISSUE THREAD

**Issue by janewilkin** [cloudhead/node-static#105]
I noticed that when using my default node-static stub file, based on the example from the README.md, the node server would run and register receiving the HTTP request, but never serve the data.  It appears that the addListener statement is no longer required.

Here's the block form the README.md

require('http').createServer(function (request, response) {
    request.addListener('end', function () {
        //
        // Serve files!
        //
        file.serve(request, response);
    }).resume();
}).listen(8080);

This is a working solution:

// Create HTTP server
var serv = http.createServer(function (req, res) {
  console.log('HTTP Connection');
  file.serve(req, res);
}).listen(8081);

**Comment by mnpenner** [comment]
I'm *still* confused why `request.addListener('end'` is in there. What's it do? Why are we waiting before serving a file?
