### ISSUE TITLE
Single page app using pushState corrupts(?) mime types

### ISSUE THREAD

**Issue by mrozbarry** [cloudhead/node-static#152]
I'm writing a single page app using node-static and webpack.  Hitting the index page works great, and even navigating is fine (since push state doesn't do a round trip to the server), however, if I'm on a virtual page, node-static attempts to interpret that as another page.  I assumed I could just force it to render the index again like this:

      public.serve(request, response, function(error, res) {
        if (error) {
          console.error('Could not serve ', request.url, error.message);
          public.serveFile('index.html', 200, {}, request, response);
        }
      });

This doesn't work, and even though the mime-type is text/html, the chrome inspector flags the initial '<' from '<!doctype html>' as unexpected.  It also tries to load my webpack script as text/html.

Is there a better way to deal with this for a light-weight single page app?

**Comment by aaronj1335** [comment]
hey that's not a bad question. one approach i've seen is to first have something like an express or connect server (or even just the bare node http server) that serves index.html to all application paths, but also does some check for like `/public/*` paths in the request (i.e. anything static), and then at that point passes the request off to node-static. so basically reversing the order of what you've got here. does that make sense?

**Comment by mrozbarry** [comment]
Just to update, I sorted out that my code was only working for 200s (when the file just existed), and after fiddling a bit, this ended up working:

      public.serve(request, response, function(error, res) {
        if (error) {
          console.error('Could not serve ', request.url, error.message);
          if ([404, 500].indexOf(error.status) >= 0) {
            public.serveFile('index.html', 404, {}, request, response);
          }
        }

I also went into index.html, and added this to the head:

    <base href="/" />

This is now working and all my assets are loading.

What was happening before was that my page actually loaded fine, but when it hit a 404, it would send either no bytes for nodia.js (since /my/pushState/url/nodia.js didn't exist), and the 404 tried to force-load my index.html (which obviously isn't javascript).
