### ISSUE TITLE
CORS support in node-static server

### ISSUE THREAD

**Issue by madhavan020985** [cloudhead/node-static#153]
When i send http requests from third party domains like,
````bash
curl -H "Origin: http://example.com" http://127.0.0.1:8080/server/app.js                                              
````
node-static server sends the files with no restriction. Is there any way, we can configure a set of third party domains to serve and block requests from all other domains? Something like CORS middleware in expressjs.

**Comment by janmonschke** [comment]
@madhavan020985 You can pass those headers into the config object:

```javascript
var staticServer = new nodeStatic.Server({
  headers: {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET',
    'Access-Control-Allow-Headers': 'Content-Type'
  }
});
```

**Comment by madhavan020985** [comment]
thanks folks.....

**Comment by trendsetter37** [comment]
Thanks.
