### ISSUE TITLE
Disable ETags

### ISSUE THREAD

**Issue by IngwiePhoenix** [cloudhead/node-static#158]
I would like to not use ETags for a variety of reasons - one being my site running using a load-balancer and ETags will differ due to different inodes and alike.

Would it be possible to introduce config options to turn off/on various Cache-headers?

Kind regards, Ingwie

**Comment by brettz9** [comment]
You can supply `-c false` on the command line or `cache: false` programmatically to disable it entirely.

To turn on the `Cache-Control` headers you want, set it to a number or object of glob patterns to max-age numbers (or just set your own headers).

Closing as that should resolve, but feel free to comment further as needed.
