### ISSUE TITLE
Version on NPM seems to be incomplete

### ISSUE THREAD

**Issue by mercmobily** [cloudhead/node-static#163]
Hi,

There are marked differences between the 0.7.6 version on Github (master branch) and the one published in NPM. Especially, it's missing the "indexFile" option (as well as a fix for a missing "var").

Please run `npm publish` to fix it!

More specifically:

    diff -r node-static ../node-static/
    Only in node-static: .git
    Only in node-static: .gitignore
    diff -r node-static/lib/node-static.js ../node-static/lib/node-static.js
    13c13
    < var Server = function (root, options) {
    ---
    > Server = function (root, options) {
    24,25d23
    <     this.options.indexFile = this.options.indexFile || "index.html";
    < 
    53c51
    <     var htmlIndex = path.join(pathname, this.options.indexFile),
    ---
    >     var htmlIndex = path.join(pathname, 'index.html'),
    Only in ../node-static/: node_modules
    Only in ../node-static/: .npmignore
    diff -r node-static/package.json ../node-static/package.json
    11c11,14
    <   "author": "Alexis Sellier <self@cloudhead.net>",
    ---
    >   "author": {
    >     "name": "Alexis Sellier",
    >     "email": "self@cloudhead.net"
    >   },
    13,14c16,23
    <     "Pablo Cantero <pablo@pablocantero.com>",
    <     "Ionică Bizău <bizauionica@gmail.com>"
    ---
    >     {
    >       "name": "Pablo Cantero",
    >       "email": "pablo@pablocantero.com"
    >     },
    >     {
    >       "name": "Ionică Bizău",
    >       "email": "bizauionica@gmail.com"
    >     }
    48c57,84
    <   }
    ---
    >   },
    >   "_id": "node-static@0.7.6",
    >   "dist": {
    >     "shasum": "ac032e40de6881fb5e4dadeed6e1d07d37268380",
    >     "tarball": "http://registry.npmjs.org/node-static/-/node-static-0.7.6.tgz"
    >   },
    >   "_from": "node-static@",
    >   "_npmVersion": "1.3.21",
    >   "_npmUser": {
    >     "name": "phstc",
    >     "email": "pablo@pablocantero.com"
    >   },
    >   "maintainers": [
    >     {
    >       "name": "cloudhead",
    >       "email": "self@cloudhead.net"
    >     },
    >     {
    >       "name": "indexzero",
    >       "email": "charlie.robbins@gmail.com"
    >     },
    >     {
    >       "name": "phstc",
    >       "email": "pablo@pablocantero.com"
    >     }
    >   ],
    >   "_shasum": "ac032e40de6881fb5e4dadeed6e1d07d37268380",
    >   "_resolved": "https://registry.npmjs.org/node-static/-/node-static-0.7.6.tgz"
    diff -r node-static/README.md ../node-static/README.md
    189,196d188
    < #### `indexFile` #
    < 
    < Choose a custom index file when serving up directories.
    < 
    < example: `{ indexFile: "index.htm" }`
    < 
    < > Defaults to `index.html`
    < 
    diff -r node-static/test/integration/node-static-test.js ../node-static/test/integration/node-static-test.js
    360,388d359
    < }).addBatch({
    <   'once an http server is listening with custom index configuration': {
    <     topic: function () {
    <       server.close();
    < 
    <       fileServer  = new static.Server(__dirname + '/../fixtures', { indexFile: "hello.txt" });
    < 
    <       server = require('http').createServer(function (request, response) {
    <         fileServer.serve(request, response);
    <       }).listen(TEST_PORT, this.callback)
    <     },
    <     'should be listening' : function(){
    <       /* This test is necessary to ensure the topic execution.
    <        * A topic without tests will be not executed */
    <       assert.isTrue(true);
    <     }
    <   }
    < }).addBatch({
    <   'serving custom index file': {
    <     topic : function(){
    <       request.get(TEST_SERVER + '/', this.callback);
    <     },
    <     'should respond with 200' : function(error, response, body){
    <       assert.equal(response.statusCode, 200);
    <     },
    <     'should respond with empty string': function(error, response, body){
    <       assert.equal(body, 'hello world');
    <     }
    <   }

**Comment by cloudhead** [comment]
Pushed 0.7.7. Cheers.
