### ISSUE TITLE
Is this module maintained?

### ISSUE THREAD

**Issue by mercmobily** [cloudhead/node-static#165]
Hi,

Is this module being actively maintained?
I can see several PR (some of them are good) just left there, plus the fact that the NPM version is not in sync.. Is anybody actively (or even half actively) looking after this module?

I just would love to know so that I can decide if I want it as a dependency, no hard feelings! :D

**Comment by cloudhead** [comment]
I check on it now and then, but it's not actively maintained. If there's a major issue (usually compatibility changes with node), someone will submit a PR and I'll merge it.
