### ISSUE TITLE
minor: Doesn't support some characters like #. Simple fix

### ISSUE THREAD

**Issue by LukeMagill** [cloudhead/node-static#170]
So, I was trying to serve an image called something like 'awsome picture #1.jpg' and it can't handle the # character. I think there are other characters it can't handle too. I fixed it locally by going to node-static.js and replacing all occurences of the function decodeURI with decodeURIComponent (there are only 2). This seems to work correctly.

**Comment by ravinggenius** [comment]
I'm also getting this issue. I'm developing a simple static site with JSPM and System.js. One of the vendor files is located at `jspm_modules/npm/es5-ext@0.10.11/string/#/contains.js`, which is requested as `jspm_modules/npm/es5-ext@0.10.11/string/%23/contains.js`. `node-static` cli cannot find the resource and returns a 404.
