### ISSUE TITLE
No v0.7.7 release

### ISSUE THREAD

**Issue by sirudog** [cloudhead/node-static#171]
Hi,

I have noticed that the latest version (0.7.7 at the moment) did not get a tagged release in this repo. The last tagged release I have found was v0.7.6
In my Jenkins CI setup I would like to get the 0.7.7 release by referencing the v0.7.7 tag, instead of cloning directly the master branch (which is at the moment the latest version = 0.7.7), so I know that even if there are newer releases, I'll always stick to that version. Can you please create a new release from master with tag v0.7.7?
Thanks in advance!

**Comment by sirudog** [comment]
@cloudhead Thanks for closing this issue without any explanation or action done... Unstaring and ditching this.

**Comment by cloudhead** [comment]
Hey, sorry about that. I don't know why I closed this issue. I've created the missing tags incase you want to give it a second chance.
