### ISSUE TITLE
Enable options to send CORS headers

### ISSUE THREAD

**Issue by tchakabam** [cloudhead/node-static#193]
... this is a necessaty when serving media-data to XHRs.

**Comment by dizel3d** [comment]
Set the headers yourself, e.g.
```
static -H '{"Access-Control-Allow-Origin": "*"}'
```

**Comment by tchakabam** [comment]
@dizel3d totally fine solution right there, thanks! :+1:  

i just thought it come in handy to just say for example `static -x`, which would in sum be a short-hand for the config you put above, to enable x-origin to anyone. analgous to the `cache` option which is also just a shorthand for a `H` option.

but it certainly is not a super important thing :)

**Comment by andruhon** [comment]
It now explodes with

SyntaxError: Unexpected token A in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\Users\andruhon\AppData\Roaming\npm\node_modules\node-static\bin\cli.js:90:46)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3

**Comment by tchakabam** [comment]
is that exactly the command which you run? 

`static -H '{"Access-Control-Allow-Origin": "*"}'`

**Comment by tchakabam** [comment]
@andruhon tested with latest version, can't repro. which version are you seeing this?

sounds more like the string you pass custom headers in on the command line is malformed, hence the JSON parse error.

**Comment by andruhon** [comment]
@tchakabam

Windows 10 PS

```
PS C:\temp\test-static> node --version
v9.2.0
PS C:\temp\test-static> gci


    Directory: C:\temp\test-static


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       22/11/2017  10:54 AM             90 index.html


PS C:\temp\test-static> npm install node-static
npm WARN saveError ENOENT: no such file or directory, open 'C:\temp\test-static\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\temp\test-static\package.json'
npm WARN test-static No description
npm WARN test-static No repository field.
npm WARN test-static No README data
npm WARN test-static No license field.

+ node-static@0.7.10
added 6 packages in 2.919s

PS C:\temp\test-static> .\node_modules\.bin\static -H '{"Access-Control-Allow-Origin": "*"}'
undefined:1
{Access-Control-Allow-Origin: *}
 ^

SyntaxError: Unexpected token A in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\temp\test-static\node_modules\node-static\bin\cli.js:90:46)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

```
PS C:\temp\test-static> npm i node-static -g
C:\Users\User\AppData\Roaming\npm\static -> C:\Users\User\AppData\Roaming\npm\node_modules\node-static\bin\cli.js
+ node-static@0.7.10
added 6 packages in 0.787s
PS C:\temp\test-static> static -H '{"Access-Control-Allow-Origin": "*"}'
undefined:1
{Access-Control-Allow-Origin: *}
 ^

SyntaxError: Unexpected token A in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\node-static\bin\cli.js:90:46)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

**Comment by andruhon** [comment]
Works fine in LWS with ubuntu xenial, so this must be a windows issue.

```
user@andr-pc: test-static$ node --version
v9.2.0
user@andr-pc: test-static$ ./node_modules/.bin/static -p 8888
serving "." at http://127.0.0.1:8888
11:31:22 [200]: /
11:31:22 [404]: /favicon.ico
^C
user@andr-pc: test-static$ ./node_modules/.bin/static -p 8888 -H '{"Access-Control-Allow-Origin": "*"}'
serving "." at http://127.0.0.1:8888
11:32:06 [200]: /
```

**Comment by tchakabam** [comment]
i can reproduce the error on linux when doing this: `static -H '{Access-Control-Allow-Origin: "*"}'`

seems that Windows is somehow removing the double-quotes around the property name maybe? :)

i think Node can't really do anything about it, the arguments must come in wrong from the shell already (i guess). 

maybe try to see if there is something you need to do in Windows shell to get that right.

**Comment by andruhon** [comment]
Ah, right, the quotes in PowerShell should be escapet even if they are not the same as string wrappers:
```PS c:\somewhere> static -H '{\"Access-Control-Allow-Origin\": \"*\"}'``` works in PS

Old good CMD does't support single quote wrappers at all, so the string should be
```c:\somewhere> static -H "{\"Access-Control-Allow-Origin\": \"*\"}"```

**Comment by tchakabam** [comment]
in the node-static readme? not sure if this is something we should document here. it seems like a pretty generic windows shell topic.

glad we we re able to work it out :) :+1:
