### ISSUE TITLE
Latest version of mime module requires ES6 support

### ISSUE THREAD

**Issue by gouldingken** [cloudhead/node-static#195]
The latest version of the "mime" module requires ES6 support (just released 9/12/2017).

The simplest solution to continue to allow broad Node.js support would be to update package.json to use more specific versioning (currently just > "mime": ">=1.2.9"). 

I guess 1.x.x would do the trick and prevent these kinds of breaking changes.

**Comment by cpsubrian** [comment]
Also, there are breaking changes in the 2.0.0 API.

**Comment by jishi** [comment]
Installing mime@1.4.0 manually in my own project pegged node-static to use the same version (because of the range) which is a workaround for now at least.

**Comment by fmalk** [comment]
I had to peg mine at 1.3.6

**Comment by cloudhead** [comment]
Fixed & published.
