### ISSUE TITLE
Latest change on mime@1.3 breaks node-static@0.7.9

### ISSUE THREAD

**Issue by fmalk** [cloudhead/node-static#199]
We had our production environment collapse because node-static wants `mime >="1.2.9"`, which introduced a breaking change

```
TypeError: mime.lookup is not a function
at Server.respond (/var/app/current/node_modules/node-static/lib/node-static.js:348:28)
at /var/app/current/node_modules/node-static/lib/node-static.js:64:22
at FSReqWrap.oncomplete (fs.js:123:15)
```

Forcing `npm install mime@1.3.6` fixed the issue for us

**Comment by cloudhead** [comment]
Fixed & published.

**Comment by jvschoen** [comment]
This worked for me! Thanks for the suggestion.
-J
