### ISSUE TITLE
SPA mode is failing if `.` is in URL

### ISSUE THREAD

**Issue by gjuchault** [cloudhead/node-static#203]
As you're using `if (argv['spa'] && request.url.indexOf(".") == -1) {` (which is here because you want to 404 on real files not found).

But ! If we use query string parameters with `.` inside, such as:
```
url.com/path/subpath?email=john.cena@gmail.com
```
then it matches the indexOf, while we still want the path to resolve as SPA.

I might open a PR when I have some time.

**Comment by gjuchault** [comment]
PR opened: #204

**Comment by brettz9** [comment]
Closed by #227.
