### ISSUE TITLE
How do I set headers?

### ISSUE THREAD

**Issue by blaasvaer** [cloudhead/node-static#216]
How to I set headers for whatever file I'd like to serve?

**Comment by brettz9** [comment]
I guess you mean per-file headers from the command line? If so, this feature does not exist. If you mean for all files, see https://github.com/cloudhead/node-static#headers-default- 

And if you mean how to do so programmatically, you can serve for individual files with https://github.com/cloudhead/node-static#serving-specific-files or within your server you can call `serve` (or perhaps set up separate `Server` instances).

**Comment by brettz9** [comment]
Closing as received no reply. Feel free to file a new issue as needed if the comment supplied did not address your concern.
